// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: instancepb/instance.proto

package instancepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArchitectureValues int32

const (
	ArchitectureValues_ARCHITECTURE_UNSPECIFIED ArchitectureValues = 0
	ArchitectureValues_i386                     ArchitectureValues = 1
	ArchitectureValues_X86_64                   ArchitectureValues = 2
	ArchitectureValues_arm64                    ArchitectureValues = 3
	ArchitectureValues_x86_64_mac               ArchitectureValues = 4
	ArchitectureValues_arm64_mac                ArchitectureValues = 5
)

// Enum value maps for ArchitectureValues.
var (
	ArchitectureValues_name = map[int32]string{
		0: "ARCHITECTURE_UNSPECIFIED",
		1: "i386",
		2: "X86_64",
		3: "arm64",
		4: "x86_64_mac",
		5: "arm64_mac",
	}
	ArchitectureValues_value = map[string]int32{
		"ARCHITECTURE_UNSPECIFIED": 0,
		"i386":                     1,
		"X86_64":                   2,
		"arm64":                    3,
		"x86_64_mac":               4,
		"arm64_mac":                5,
	}
)

func (x ArchitectureValues) Enum() *ArchitectureValues {
	p := new(ArchitectureValues)
	*p = x
	return p
}

func (x ArchitectureValues) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArchitectureValues) Descriptor() protoreflect.EnumDescriptor {
	return file_instancepb_instance_proto_enumTypes[0].Descriptor()
}

func (ArchitectureValues) Type() protoreflect.EnumType {
	return &file_instancepb_instance_proto_enumTypes[0]
}

func (x ArchitectureValues) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArchitectureValues.Descriptor instead.
func (ArchitectureValues) EnumDescriptor() ([]byte, []int) {
	return file_instancepb_instance_proto_rawDescGZIP(), []int{0}
}

type AttachmentStatus int32

const (
	AttachmentStatus_AttachmentStatus_UNSPECIFIED AttachmentStatus = 0
	AttachmentStatus_attaching                    AttachmentStatus = 1
	AttachmentStatus_attached                     AttachmentStatus = 2
	AttachmentStatus_detaching                    AttachmentStatus = 3
	AttachmentStatus_detached                     AttachmentStatus = 4
)

// Enum value maps for AttachmentStatus.
var (
	AttachmentStatus_name = map[int32]string{
		0: "AttachmentStatus_UNSPECIFIED",
		1: "attaching",
		2: "attached",
		3: "detaching",
		4: "detached",
	}
	AttachmentStatus_value = map[string]int32{
		"AttachmentStatus_UNSPECIFIED": 0,
		"attaching":                    1,
		"attached":                     2,
		"detaching":                    3,
		"detached":                     4,
	}
)

func (x AttachmentStatus) Enum() *AttachmentStatus {
	p := new(AttachmentStatus)
	*p = x
	return p
}

func (x AttachmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttachmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_instancepb_instance_proto_enumTypes[1].Descriptor()
}

func (AttachmentStatus) Type() protoreflect.EnumType {
	return &file_instancepb_instance_proto_enumTypes[1]
}

func (x AttachmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttachmentStatus.Descriptor instead.
func (AttachmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_instancepb_instance_proto_rawDescGZIP(), []int{1}
}

// information message about the status of the instance.
type StatusUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instancepb_instance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_instancepb_instance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_instancepb_instance_proto_rawDescGZIP(), []int{0}
}

func (x *StatusUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request message to get instances by region.
type GetInstancesByRegionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
}

func (x *GetInstancesByRegionRequest) Reset() {
	*x = GetInstancesByRegionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instancepb_instance_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInstancesByRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstancesByRegionRequest) ProtoMessage() {}

func (x *GetInstancesByRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_instancepb_instance_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstancesByRegionRequest.ProtoReflect.Descriptor instead.
func (*GetInstancesByRegionRequest) Descriptor() ([]byte, []int) {
	return file_instancepb_instance_proto_rawDescGZIP(), []int{1}
}

func (x *GetInstancesByRegionRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

// Response message containing instances in a specific region.
type GetInstancesByRegionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of instances in the specified region.
	Instances []*Instance `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
}

func (x *GetInstancesByRegionResponse) Reset() {
	*x = GetInstancesByRegionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instancepb_instance_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInstancesByRegionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstancesByRegionResponse) ProtoMessage() {}

func (x *GetInstancesByRegionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_instancepb_instance_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstancesByRegionResponse.ProtoReflect.Descriptor instead.
func (*GetInstancesByRegionResponse) Descriptor() ([]byte, []int) {
	return file_instancepb_instance_proto_rawDescGZIP(), []int{2}
}

func (x *GetInstancesByRegionResponse) GetInstances() []*Instance {
	if x != nil {
		return x.Instances
	}
	return nil
}

// Instance message.
type Instance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AmiLaunchIndex      int32                         `protobuf:"varint,1,opt,name=AmiLaunchIndex,proto3" json:"AmiLaunchIndex,omitempty"`
	Architecture        ArchitectureValues            `protobuf:"varint,2,opt,name=Architecture,proto3,enum=instancepb.ArchitectureValues" json:"Architecture,omitempty"`
	BlockDeviceMappings []*InstanceBlockDeviceMapping `protobuf:"bytes,3,rep,name=BlockDeviceMappings,proto3" json:"BlockDeviceMappings,omitempty"`
}

func (x *Instance) Reset() {
	*x = Instance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instancepb_instance_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_instancepb_instance_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_instancepb_instance_proto_rawDescGZIP(), []int{3}
}

func (x *Instance) GetAmiLaunchIndex() int32 {
	if x != nil {
		return x.AmiLaunchIndex
	}
	return 0
}

func (x *Instance) GetArchitecture() ArchitectureValues {
	if x != nil {
		return x.Architecture
	}
	return ArchitectureValues_ARCHITECTURE_UNSPECIFIED
}

func (x *Instance) GetBlockDeviceMappings() []*InstanceBlockDeviceMapping {
	if x != nil {
		return x.BlockDeviceMappings
	}
	return nil
}

type InstanceBlockDeviceMapping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceName string                  `protobuf:"bytes,1,opt,name=DeviceName,proto3" json:"DeviceName,omitempty"`
	Ebs        *EbsInstanceBlockDevice `protobuf:"bytes,2,opt,name=Ebs,proto3" json:"Ebs,omitempty"`
}

func (x *InstanceBlockDeviceMapping) Reset() {
	*x = InstanceBlockDeviceMapping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instancepb_instance_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstanceBlockDeviceMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceBlockDeviceMapping) ProtoMessage() {}

func (x *InstanceBlockDeviceMapping) ProtoReflect() protoreflect.Message {
	mi := &file_instancepb_instance_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceBlockDeviceMapping.ProtoReflect.Descriptor instead.
func (*InstanceBlockDeviceMapping) Descriptor() ([]byte, []int) {
	return file_instancepb_instance_proto_rawDescGZIP(), []int{4}
}

func (x *InstanceBlockDeviceMapping) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *InstanceBlockDeviceMapping) GetEbs() *EbsInstanceBlockDevice {
	if x != nil {
		return x.Ebs
	}
	return nil
}

type EbsInstanceBlockDevice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttachTime          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=AttachTime,proto3" json:"AttachTime,omitempty"`
	DeleteOnTermination bool                   `protobuf:"varint,2,opt,name=DeleteOnTermination,proto3" json:"DeleteOnTermination,omitempty"`
	Status              AttachmentStatus       `protobuf:"varint,3,opt,name=Status,proto3,enum=instancepb.AttachmentStatus" json:"Status,omitempty"`
	VolumeId            string                 `protobuf:"bytes,4,opt,name=VolumeId,proto3" json:"VolumeId,omitempty"`
}

func (x *EbsInstanceBlockDevice) Reset() {
	*x = EbsInstanceBlockDevice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instancepb_instance_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EbsInstanceBlockDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EbsInstanceBlockDevice) ProtoMessage() {}

func (x *EbsInstanceBlockDevice) ProtoReflect() protoreflect.Message {
	mi := &file_instancepb_instance_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EbsInstanceBlockDevice.ProtoReflect.Descriptor instead.
func (*EbsInstanceBlockDevice) Descriptor() ([]byte, []int) {
	return file_instancepb_instance_proto_rawDescGZIP(), []int{5}
}

func (x *EbsInstanceBlockDevice) GetAttachTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AttachTime
	}
	return nil
}

func (x *EbsInstanceBlockDevice) GetDeleteOnTermination() bool {
	if x != nil {
		return x.DeleteOnTermination
	}
	return false
}

func (x *EbsInstanceBlockDevice) GetStatus() AttachmentStatus {
	if x != nil {
		return x.Status
	}
	return AttachmentStatus_AttachmentStatus_UNSPECIFIED
}

func (x *EbsInstanceBlockDevice) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

var File_instancepb_instance_proto protoreflect.FileDescriptor

var file_instancepb_instance_proto_rawDesc = []byte{
	0x0a, 0x19, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x70, 0x62, 0x2f, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x35, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x73, 0x42, 0x79, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x22, 0x52, 0x0a, 0x1c, 0x47, 0x65, 0x74,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x42, 0x79, 0x52, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x52, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x22, 0xd0, 0x01,
	0x0a, 0x08, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x41, 0x6d,
	0x69, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0e, 0x41, 0x6d, 0x69, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x42, 0x0a, 0x0c, 0x41, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x70, 0x62, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x0c, 0x41, 0x72, 0x63, 0x68, 0x69, 0x74,
	0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x58, 0x0a, 0x13, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x70, 0x62,
	0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x13, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73,
	0x22, 0x72, 0x0a, 0x1a, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x1e,
	0x0a, 0x0a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x34,
	0x0a, 0x03, 0x45, 0x62, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x70, 0x62, 0x2e, 0x45, 0x62, 0x73, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x03, 0x45, 0x62, 0x73, 0x22, 0xd8, 0x01, 0x0a, 0x16, 0x45, 0x62, 0x73, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3a, 0x0a, 0x0a, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0a, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x13, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x6e, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4f, 0x6e, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x70, 0x62, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x2a,
	0x72, 0x0a, 0x12, 0x41, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x18, 0x41, 0x52, 0x43, 0x48, 0x49, 0x54, 0x45,
	0x43, 0x54, 0x55, 0x52, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x69, 0x33, 0x38, 0x36, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x58, 0x38, 0x36, 0x5f, 0x36, 0x34, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x61, 0x72, 0x6d,
	0x36, 0x34, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x78, 0x38, 0x36, 0x5f, 0x36, 0x34, 0x5f, 0x6d,
	0x61, 0x63, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x61, 0x72, 0x6d, 0x36, 0x34, 0x5f, 0x6d, 0x61,
	0x63, 0x10, 0x05, 0x2a, 0x6e, 0x0a, 0x10, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x1c, 0x41, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x61, 0x74, 0x74,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x61, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x65, 0x64, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x64, 0x65, 0x74, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x67, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x64, 0x65, 0x74, 0x61, 0x63, 0x68, 0x65,
	0x64, 0x10, 0x04, 0x32, 0xd5, 0x01, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x12, 0x6d, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73,
	0x42, 0x79, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x73, 0x42, 0x79, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x28, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x42, 0x79, 0x52, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12,
	0x5a, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x73, 0x12, 0x27, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x42, 0x79,
	0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x33, 0x5a, 0x31, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x6d,
	0x6f, 0x64, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_instancepb_instance_proto_rawDescOnce sync.Once
	file_instancepb_instance_proto_rawDescData = file_instancepb_instance_proto_rawDesc
)

func file_instancepb_instance_proto_rawDescGZIP() []byte {
	file_instancepb_instance_proto_rawDescOnce.Do(func() {
		file_instancepb_instance_proto_rawDescData = protoimpl.X.CompressGZIP(file_instancepb_instance_proto_rawDescData)
	})
	return file_instancepb_instance_proto_rawDescData
}

var file_instancepb_instance_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_instancepb_instance_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_instancepb_instance_proto_goTypes = []interface{}{
	(ArchitectureValues)(0),              // 0: instancepb.ArchitectureValues
	(AttachmentStatus)(0),                // 1: instancepb.AttachmentStatus
	(*StatusUpdate)(nil),                 // 2: instancepb.StatusUpdate
	(*GetInstancesByRegionRequest)(nil),  // 3: instancepb.GetInstancesByRegionRequest
	(*GetInstancesByRegionResponse)(nil), // 4: instancepb.GetInstancesByRegionResponse
	(*Instance)(nil),                     // 5: instancepb.Instance
	(*InstanceBlockDeviceMapping)(nil),   // 6: instancepb.InstanceBlockDeviceMapping
	(*EbsInstanceBlockDevice)(nil),       // 7: instancepb.EbsInstanceBlockDevice
	(*timestamppb.Timestamp)(nil),        // 8: google.protobuf.Timestamp
}
var file_instancepb_instance_proto_depIdxs = []int32{
	5, // 0: instancepb.GetInstancesByRegionResponse.instances:type_name -> instancepb.Instance
	0, // 1: instancepb.Instance.Architecture:type_name -> instancepb.ArchitectureValues
	6, // 2: instancepb.Instance.BlockDeviceMappings:type_name -> instancepb.InstanceBlockDeviceMapping
	7, // 3: instancepb.InstanceBlockDeviceMapping.Ebs:type_name -> instancepb.EbsInstanceBlockDevice
	8, // 4: instancepb.EbsInstanceBlockDevice.AttachTime:type_name -> google.protobuf.Timestamp
	1, // 5: instancepb.EbsInstanceBlockDevice.Status:type_name -> instancepb.AttachmentStatus
	3, // 6: instancepb.instance.GetInstancesByRegion:input_type -> instancepb.GetInstancesByRegionRequest
	3, // 7: instancepb.instance.SendStatusUpdates:input_type -> instancepb.GetInstancesByRegionRequest
	4, // 8: instancepb.instance.GetInstancesByRegion:output_type -> instancepb.GetInstancesByRegionResponse
	2, // 9: instancepb.instance.SendStatusUpdates:output_type -> instancepb.StatusUpdate
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_instancepb_instance_proto_init() }
func file_instancepb_instance_proto_init() {
	if File_instancepb_instance_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_instancepb_instance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_instancepb_instance_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInstancesByRegionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_instancepb_instance_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInstancesByRegionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_instancepb_instance_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Instance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_instancepb_instance_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstanceBlockDeviceMapping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_instancepb_instance_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EbsInstanceBlockDevice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_instancepb_instance_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_instancepb_instance_proto_goTypes,
		DependencyIndexes: file_instancepb_instance_proto_depIdxs,
		EnumInfos:         file_instancepb_instance_proto_enumTypes,
		MessageInfos:      file_instancepb_instance_proto_msgTypes,
	}.Build()
	File_instancepb_instance_proto = out.File
	file_instancepb_instance_proto_rawDesc = nil
	file_instancepb_instance_proto_goTypes = nil
	file_instancepb_instance_proto_depIdxs = nil
}
